# Generated by Django 4.2.3 on 2023-08-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TypingExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Content for the typing exercise",
                        verbose_name="Exercise Content",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Typing Exercise",
                        help_text="Title or name of the exercise",
                        max_length=200,
                        verbose_name="Exercise Title",
                    ),
                ),
                (
                    "date_added",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date when the exercise was added",
                        verbose_name="Date Added",
                    ),
                ),
            ],
            options={
                "verbose_name": "Typing Exercise",
                "verbose_name_plural": "Typing Exercises",
                "ordering": ["-date_added"],
            },
        ),
    ]
