# Generated by Django 4.2.3 on 2023-08-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_typingexercise"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "exercise_id",
                    models.CharField(
                        max_length=10, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("lesson_id", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("tasks", models.TextField()),
            ],
        ),
    ]
